### ISSUE TITLE
Why is JobThread marked as daemon?

### ISSUE THREAD

**Issue by bukefalos** [Coreoz/Wisp#2]
Hi, I was looking for simple scheduler library supporting cron expressions and I came across this one. I have a question though:

How is scheduler intended to work when JobThread is marked as daemon? In my very simple scenario I just create Scheduler and schedule some jobs that I want to run regularly every day, but after main method finishes, JVM terminates because there are no non-daemon threads. What is the reasoning behind marking these threads as daemon? I think JobThread should not be marked as daemon by default or am I missing something?

**Comment by amanteaux** [comment]
Thank you for this issue.
You are right, it makes more sense to run threads as non-daemon.

**Comment by amanteaux** [comment]
Fixed in version 2.0.0
