### ISSUE TITLE
Fix Automatic-Module-Name

### ISSUE THREAD

**Issue by mintdaniel42** [Coreoz/Wisp#29]
If you revert 8bfff70816a222930c719182b0198914c539d47e then the automatic module name should work. It does not work on master (8bfff70816a222930c719182b0198914c539d47e) but on 1bc85164dd it does as intended

**Comment by amanteaux** [comment]
How do you test it currently?

**Comment by mintdaniel42** [comment]
Oh I see, I was testing via Jitpack Commit tag. This explains why it works in the original commit but not in the new version. My bad 🫤
