### ISSUE TITLE
Wait for job to complete 

### ISSUE THREAD

**Issue by muhdkhokhar** [Coreoz/Wisp#3]
I have a job to run every 5 seconds but I want to wait for it finish before going next run

public class CustomJob implements Runnable {

    private JobVO jobVO;

    public CustomJob(JobVO jobVO) {
        this.jobVO = jobVO;
    }

    public void run() {

        System.out.println("Job is running..." + jobVO.getName());
        try {
            Thread.sleep(1000L);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}

It ignore thread.sleep and run again.

**Comment by amanteaux** [comment]
Are you sure the job is not finished before it is scheduled again? I am almost sure there is a unit test about that.

**Comment by muhdkhokhar** [comment]
I  am so sorry. Its working fine. It was my mistake.

**Comment by amanteaux** [comment]
No problem, thank you for your check :)
