### ISSUE TITLE
Timezone for each job

### ISSUE THREAD

**Issue by muhdkhokhar** [Coreoz/Wisp#4]
Hi

I want to schedule a job but the cron expression would be different for eac job and timezone. 

Can I provide the tiemzone to the job?

**Comment by amanteaux** [comment]
There is not built-in tool currently. So if you need it now, you can copy/paste the `CronSchedule` class in your project and change line 49 with the timezone you need.

In the future I think we will add an extra constructor to `CronSchedule` to enable to customize the timezone.

**Comment by muhdkhokhar** [comment]
Thanks. I will do this.

**Comment by amanteaux** [comment]
And if you are interested, in the next release (in a week or two), there will be an constructor to customize the timezone of `CronSchedule` :)

**Comment by amanteaux** [comment]
Actually I forgot to put the change in the 2.1.0 version :(
It will definitely be in the next release.

**Comment by amanteaux** [comment]
Released in Wisp 2.2.0
