### ISSUE TITLE
First of all, I love your library ....but help

### ISSUE THREAD

**Issue by marklapasa** [Coreoz/Wisp#9]
I am developing a Kotlin app on JVM and I'm running into the above issues trying to create a basic CronSchedule as follows:

![image](https://user-images.githubusercontent.com/4932453/88753952-8269eb80-d12b-11ea-92f5-6a485484f1a7.png)

I know this is a Java library but you wouldn't happen to know how to get this working?

![image](https://user-images.githubusercontent.com/4932453/88753844-52224d00-d12b-11ea-96e7-6bc507b1ed75.png)

The Fixed schedule works beautifully but Cron in Kotlin would really put it over the top.

**Comment by marklapasa** [comment]
For any future Kotlin users out there, here's an implementation of Schedule interface that works

![image](https://user-images.githubusercontent.com/4932453/88876046-71cf7900-d1f0-11ea-974e-5871b2a4aa8e.png)

**Comment by amanteaux** [comment]
Hi @marklapasa,

Thank you for your interest in this library!
I did not actually get why you had an issue with Kotlin. Kotlin should run without issue any Java library.

Cheers,
Aurélien

**Comment by marklapasa** [comment]
An update. I made a horrible mistake.

I actually used version 3.1.0 of the cron-utils library when logging this bug.
Using the latest _com.cronutils:cron-utils:9.1.1_ actually has no issues in Kotlin.

Everything else logged in this ticket is irrelevant. My apologies.

**Comment by amanteaux** [comment]
Thank you a lot for these precisions! No need to apologies!
